CREATE TABLE IF NOT EXISTS wtbg_players (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    license VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,

    level INT UNSIGNED NOT NULL DEFAULT 1,
    xp BIGINT UNSIGNED NOT NULL DEFAULT 0,

    matches INT UNSIGNED NOT NULL DEFAULT 0,
    wins INT UNSIGNED NOT NULL DEFAULT 0,
    kills INT UNSIGNED NOT NULL DEFAULT 0,
    deaths INT UNSIGNED NOT NULL DEFAULT 0,
    assists INT UNSIGNED NOT NULL DEFAULT 0,
    damage BIGINT UNSIGNED NOT NULL DEFAULT 0,
    headshots INT UNSIGNED NOT NULL DEFAULT 0,
    top3 INT UNSIGNED NOT NULL DEFAULT 0,
    total_placement BIGINT UNSIGNED NOT NULL DEFAULT 0,
    longest_kill DECIMAL(10,2) NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    UNIQUE KEY uq_wtbg_players_license (license)
);
